### ISSUE TITLE
Vtx + PCC fit

### ISSUE THREAD

**Issue by capalmer85** [CMS-LUMI-POG/VdMFramework#21]
We need a clean PR for this. @gkrintir please make a fresh checkout and PR with minimal set of changes.  I think you should be able to use https://github.com/CMS-LUMI-POG/VdMFramework/blob/master/May2016Scans_Configs/vdmDriverII_Config_PCC_4954.json for testing.

**Comment by gkrintir** [comment]
Hi @capalmer85 

PR: https://github.com/CMS-LUMI-POG/VdMFramework/pull/22

**Comment by capalmer85** [comment]
Resolved by #22
